// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfxeupdsvklttxqqccth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeGV1cGRzdmtsdHR4cXFjY3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzcxMzUsImV4cCI6MjA1OTk1MzEzNX0.dG3vupkNYc2q5pd6OY3qlBMx17xl2xsO3YYiCWXv0zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);